# -*- coding: utf-8 -*-
"""LCM Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/145vaew5Clc7ro-PyJDpoFOiFuStckOlg
"""

for i in range(int(input())):
  l, r = map(int, input().split())
  if r - l < l:
    print(-1, -1)
  else:
    print(l, r - r % l)