# -*- coding: utf-8 -*-
"""Alchemy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

f = open("alchemy_input.txt").read()
main = f.split("\n")

testcases = int(main[0])
testcases
len_array =[]
string_array = []

i = 0
for _ in range(testcases):
  len_array.append(int(main[i + 1]))
  i += 2

j = 1
for _ in range(testcases):
  string_array.append(main[j + 1])
  j += 2

arr = []
for _ in range(testcases):
  n = len_array[_]
  s = string_array[_]
  while 1:
    if n == 1:
      arr.append("Case #" + str(_ + 1) + ": Y")
      break
    elif s.count("A") == n or s.count("B") == n:
      arr.append("Case #" + str(_ + 1) + ": N")
      break
    else:
      s = s.replace("AAB", "A")
      s = s.replace("ABA", "A")
      s = s.replace("ABB", "B")
      s = s.replace("BBA", "B")
      s = s.replace("BAB", "B")
      s = s.replace("BAA", "A")

      n = len(s)

with open('output2.txt', mode='wt', encoding='utf-8') as myfile:
    myfile.write('\n'.join(arr))

