# -*- coding: utf-8 -*-
"""Travel Restrictions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNsrkHbqbJughG_BUWa7znxu0PZJ-dCF
"""

f = open("travel_restrictions_input.txt").read()
main = f.split("\n")

len = []
incoming = []
outgoing = []
i = 0

testcases = int(main[0])
for _ in range(testcases):
  len.append(int(main[i + 1]))
  incoming.append(main[i + 2])
  outgoing.append(main[i + 3])
  
  i += 3

final_res = []

#logic 2
for _ in range(testcases):
  n = len[_]
  I = incoming[_]
  O = outgoing[_]
  res = [["N" for i in range(n)] for j in range(n)]
  res
  for i in range(n):
    if O[i] == "N":
      res [i][i] = "Y"
      continue
    else:
      for j in reversed(range(i)):
        if I[j] == "N":
          break
        elif I[j] == "Y" and O[j] == "N":
          res[i][j] = "Y"
          break
        else:
          res[i][j] = "Y"

      for j in range(i + 1, n):
        if I[j] == "N":
          break
        elif I[j] == "Y" and O[j] == "N":
          res[i][j] = "Y"
          break
        else:
          res[i][j] = "Y"

    res[i][i] = "Y"
      
  new_res = ["".join(res[x]) for x in range(n)]
  final_res.append(new_res)

with open('final_output_1.txt', mode='wt', encoding='utf-8') as myfile:
    for i in range(testcases):
      myfile.write("Case #{n}: \n".format(n = i + 1))
      myfile.write('\n'.join(final_res[i]))
      myfile.write("\n")