# -*- coding: utf-8 -*-
"""Bit Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

n = int(input())
if n == 0:
  print("0")
else:
  print(2**n % (10**9 + 7))

