# -*- coding: utf-8 -*-
"""Increasing Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

n = int(input())
nums = list(map(int, input().split()))
sum = 0
for i in range(n - 1):
  if nums[i + 1] >= nums[i]: 
    continue
  else:
     sum += abs(nums[i + 1] - nums[i])
     nums[i] , nums[i + 1] = nums[i + 1], nums[i]
print(sum)

