# -*- coding: utf-8 -*-
"""Number Spiral.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

for _ in range(int(input())):
  x, y = map(int, input().split())
  num = max(x, y)
  if x > y:
    if num % 2 == 1:
      print((num-1)**2 + y)
    else:
      print(num**2 - (y - 1))
  elif y > x:
    if num % 2 == 0:
      print((num - 1)**2 + x)
    else:
      print((num**2) - (x - 1))
  else:
    if num % 2 == 0:
      print(num**2 - (x - 1))
    else:
      print((num - 1)**2 + x)