# -*- coding: utf-8 -*-
"""Repetitions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

n = input()
count = 0
max_count = 0
for i in range(len(n) - 1):
  if n[i+1] == n[i]:
    count += 1
  else:
    max_count = max(max_count, count)
    count = 0
  max_count = max(max_count, count)
print(max_count + 1)

