# -*- coding: utf-8 -*-
"""Two Knights.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

for i in range(1, int(input()) + 1):
  print( (i**2 * (i**2 - 1))//2 - (4 * (i - 1) * (i - 2)) )

