# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVGYzjRqf81TI6FKlE6YL9DHcPAvR4NL
"""

n = int(input())
print(n, end = " ")
while n != 1:
  if n%2 == 0:
    n = n//2
  else:
    n = n * 3 + 1
  print(n, end = " ")

